package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name="candidate"
    ,catalog="evoting"
)
public class Candidate  implements java.io.Serializable {


     private Integer candidateId;
     private Party party;
     private Seat seat;
     private String candidateName;

    public Candidate() {
    }

    public Candidate(Party party, Seat seat, String candidateName) {
       this.party = party;
       this.seat = seat;
       this.candidateName = candidateName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="candidate_id", unique=true, nullable=false)
    public Integer getCandidateId() {
        return this.candidateId;
    }
    
    public void setCandidateId(Integer candidateId) {
        this.candidateId = candidateId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="party_id")
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seat_id")
    public Seat getSeat() {
        return this.seat;
    }
    
    public void setSeat(Seat seat) {
        this.seat = seat;
    }

    
    @Column(name="candidate_name", length=45)
    public String getCandidateName() {
        return this.candidateName;
    }
    
    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName;
    }




}


