package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name="district"
    ,catalog="evoting"
)
public class District  implements java.io.Serializable {


     private Integer districtId;
     private Division division;
     private String districtName;
     private Set upazillas = new HashSet(0);
     private Set seats = new HashSet(0);

    public District() {
    }

    public District(Division division, String districtName, Set upazillas, Set seats) {
       this.division = division;
       this.districtName = districtName;
       this.upazillas = upazillas;
       this.seats = seats;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="district_id", unique=true, nullable=false)
    public Integer getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="division_id")
    public Division getDivision() {
        return this.division;
    }
    
    public void setDivision(Division division) {
        this.division = division;
    }

    
    @Column(name="district_name", length=45)
    public String getDistrictName() {
        return this.districtName;
    }
    
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="district")
    public Set getUpazillas() {
        return this.upazillas;
    }
    
    public void setUpazillas(Set upazillas) {
        this.upazillas = upazillas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="district")
    public Set getSeats() {
        return this.seats;
    }
    
    public void setSeats(Set seats) {
        this.seats = seats;
    }




}


