package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name="division"
    ,catalog="evoting"
)
public class Division  implements java.io.Serializable {


     private Integer divisionId;
     private String divisionName;
     private Set districts = new HashSet(0);

    public Division() {
    }

    public Division(String divisionName, Set districts) {
       this.divisionName = divisionName;
       this.districts = districts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="division_id", unique=true, nullable=false)
    public Integer getDivisionId() {
        return this.divisionId;
    }
    
    public void setDivisionId(Integer divisionId) {
        this.divisionId = divisionId;
    }

    
    @Column(name="division_name", length=45)
    public String getDivisionName() {
        return this.divisionName;
    }
    
    public void setDivisionName(String divisionName) {
        this.divisionName = divisionName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="division")
    public Set getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Set districts) {
        this.districts = districts;
    }




}


