package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Election generated by hbm2java
 */
@Entity
@Table(name="election"
    ,catalog="evoting"
)
public class Election  implements java.io.Serializable {


     private Integer electionId;
     private String electionType;
     private Date date;
     private Date votingStartTime;
     private Date votingEndTime;
     private int isActive;

    public Election() {
    }

	
    public Election(Date votingEndTime, int isActive) {
        this.votingEndTime = votingEndTime;
        this.isActive = isActive;
    }
    public Election(String electionType, Date date, Date votingStartTime, Date votingEndTime, int isActive) {
       this.electionType = electionType;
       this.date = date;
       this.votingStartTime = votingStartTime;
       this.votingEndTime = votingEndTime;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="election_id", unique=true, nullable=false)
    public Integer getElectionId() {
        return this.electionId;
    }
    
    public void setElectionId(Integer electionId) {
        this.electionId = electionId;
    }

    
    @Column(name="election_type", length=20)
    public String getElectionType() {
        return this.electionType;
    }
    
    public void setElectionType(String electionType) {
        this.electionType = electionType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="voting_start_time", length=19)
    public Date getVotingStartTime() {
        return this.votingStartTime;
    }
    
    public void setVotingStartTime(Date votingStartTime) {
        this.votingStartTime = votingStartTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="voting_end_time", nullable=false, length=19)
    public Date getVotingEndTime() {
        return this.votingEndTime;
    }
    
    public void setVotingEndTime(Date votingEndTime) {
        this.votingEndTime = votingEndTime;
    }

    
    @Column(name="isActive", nullable=false)
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }




}


