package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Party generated by hbm2java
 */
@Entity
@Table(name="party"
    ,catalog="evoting"
)
public class Party  implements java.io.Serializable {


     private Integer partyId;
     private String partyName;
     private byte[] partySymbol;
     private Set candidates = new HashSet(0);

    public Party() {
    }

    public Party(String partyName, byte[] partySymbol, Set candidates) {
       this.partyName = partyName;
       this.partySymbol = partySymbol;
       this.candidates = candidates;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="party_id", unique=true, nullable=false)
    public Integer getPartyId() {
        return this.partyId;
    }
    
    public void setPartyId(Integer partyId) {
        this.partyId = partyId;
    }

    
    @Column(name="party_name", length=45)
    public String getPartyName() {
        return this.partyName;
    }
    
    public void setPartyName(String partyName) {
        this.partyName = partyName;
    }

    
    @Column(name="party_symbol")
    public byte[] getPartySymbol() {
        return this.partySymbol;
    }
    
    public void setPartySymbol(byte[] partySymbol) {
        this.partySymbol = partySymbol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="party")
    public Set getCandidates() {
        return this.candidates;
    }
    
    public void setCandidates(Set candidates) {
        this.candidates = candidates;
    }




}


