package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name="seat"
    ,catalog="evoting"
)
public class Seat  implements java.io.Serializable {


     private Integer seatId;
     private District district;
     private String seatName;
     private Set candidates = new HashSet(0);

    public Seat() {
    }

    public Seat(District district, String seatName, Set candidates) {
       this.district = district;
       this.seatName = seatName;
       this.candidates = candidates;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="seat_id", unique=true, nullable=false)
    public Integer getSeatId() {
        return this.seatId;
    }
    
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="district_id")
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }

    
    @Column(name="seat_name", length=45)
    public String getSeatName() {
        return this.seatName;
    }
    
    public void setSeatName(String seatName) {
        this.seatName = seatName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seat")
    public Set getCandidates() {
        return this.candidates;
    }
    
    public void setCandidates(Set candidates) {
        this.candidates = candidates;
    }




}


