package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Upazilla generated by hbm2java
 */
@Entity
@Table(name="upazilla"
    ,catalog="evoting"
)
public class Upazilla  implements java.io.Serializable {


     private Integer upazillaId;
     private District district;
     private String upazillaName;
     private Set unions = new HashSet(0);

    public Upazilla() {
    }

    public Upazilla(District district, String upazillaName, Set unions) {
       this.district = district;
       this.upazillaName = upazillaName;
       this.unions = unions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="upazilla_id", unique=true, nullable=false)
    public Integer getUpazillaId() {
        return this.upazillaId;
    }
    
    public void setUpazillaId(Integer upazillaId) {
        this.upazillaId = upazillaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="district_id")
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }

    
    @Column(name="upazilla_name", length=45)
    public String getUpazillaName() {
        return this.upazillaName;
    }
    
    public void setUpazillaName(String upazillaName) {
        this.upazillaName = upazillaName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="upazilla")
    public Set getUnions() {
        return this.unions;
    }
    
    public void setUnions(Set unions) {
        this.unions = unions;
    }




}


