package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VoteCenter generated by hbm2java
 */
@Entity
@Table(name="vote_center"
    ,catalog="evoting"
)
public class VoteCenter  implements java.io.Serializable {


     private Integer voteCenterId;
     private Ward ward;
     private String voteCenterName;

    public VoteCenter() {
    }

    public VoteCenter(Ward ward, String voteCenterName) {
       this.ward = ward;
       this.voteCenterName = voteCenterName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vote_center_id", unique=true, nullable=false)
    public Integer getVoteCenterId() {
        return this.voteCenterId;
    }
    
    public void setVoteCenterId(Integer voteCenterId) {
        this.voteCenterId = voteCenterId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ward_id")
    public Ward getWard() {
        return this.ward;
    }
    
    public void setWard(Ward ward) {
        this.ward = ward;
    }

    
    @Column(name="vote_center_name", length=45)
    public String getVoteCenterName() {
        return this.voteCenterName;
    }
    
    public void setVoteCenterName(String voteCenterName) {
        this.voteCenterName = voteCenterName;
    }




}


