package com.ness.entity;
// Generated May 4, 2017 9:52:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VoterInfo generated by hbm2java
 */
@Entity
@Table(name="voter_info"
    ,catalog="evoting"
)
public class VoterInfo  implements java.io.Serializable {


     private Integer voterId;
     private Ward ward;
     private Integer nid;
     private String FName;
     private String LName;
     private String sex;
     private Date dob;
     private String fatherName;
     private String motherName;
     private String bloodGroup;
     private String age;
     private String occupation;
     private String religion;
     private Boolean maritalStatus;
     private String nationality;
     private String presentAddress;
     private String permanentAddress;
     private byte[] voterImage;
     private String password;
     private String email;
     private Integer isVoted;

    public VoterInfo() {
    }

    public VoterInfo(Ward ward, Integer nid, String FName, String LName, String sex, Date dob, String fatherName, String motherName, String bloodGroup, String age, String occupation, String religion, Boolean maritalStatus, String nationality, String presentAddress, String permanentAddress, byte[] voterImage, String password, String email, Integer isVoted) {
       this.ward = ward;
       this.nid = nid;
       this.FName = FName;
       this.LName = LName;
       this.sex = sex;
       this.dob = dob;
       this.fatherName = fatherName;
       this.motherName = motherName;
       this.bloodGroup = bloodGroup;
       this.age = age;
       this.occupation = occupation;
       this.religion = religion;
       this.maritalStatus = maritalStatus;
       this.nationality = nationality;
       this.presentAddress = presentAddress;
       this.permanentAddress = permanentAddress;
       this.voterImage = voterImage;
       this.password = password;
       this.email = email;
       this.isVoted = isVoted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="voter_id", unique=true, nullable=false)
    public Integer getVoterId() {
        return this.voterId;
    }
    
    public void setVoterId(Integer voterId) {
        this.voterId = voterId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ward_id")
    public Ward getWard() {
        return this.ward;
    }
    
    public void setWard(Ward ward) {
        this.ward = ward;
    }

    
    @Column(name="nid")
    public Integer getNid() {
        return this.nid;
    }
    
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    
    @Column(name="f_name", length=45)
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }

    
    @Column(name="l_name", length=45)
    public String getLName() {
        return this.LName;
    }
    
    public void setLName(String LName) {
        this.LName = LName;
    }

    
    @Column(name="sex", length=10)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="father_name", length=45)
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    
    @Column(name="mother_name", length=45)
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    
    @Column(name="blood_group", length=45)
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    
    @Column(name="age", length=45)
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }

    
    @Column(name="occupation", length=45)
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="religion", length=45)
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }

    
    @Column(name="marital_status")
    public Boolean getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(Boolean maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    
    @Column(name="nationality", length=45)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="present_address", length=150)
    public String getPresentAddress() {
        return this.presentAddress;
    }
    
    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }

    
    @Column(name="permanent_address", length=150)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }
    
    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    
    @Column(name="voter_image")
    public byte[] getVoterImage() {
        return this.voterImage;
    }
    
    public void setVoterImage(byte[] voterImage) {
        this.voterImage = voterImage;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="isVoted")
    public Integer getIsVoted() {
        return this.isVoted;
    }
    
    public void setIsVoted(Integer isVoted) {
        this.isVoted = isVoted;
    }




}


